# mkdocs.yml

# -------------------------------------------------------------
# CONFIGURACIÓN GENERAL DEL SITIO
# -------------------------------------------------------------
site_name: Unidad 1 - Tarea Isidro

# -------------------------------------------------------------
# ESTRUCTURA DE NAVEGACIÓN (MENÚ)
# -------------------------------------------------------------

nav:
  - Inicio: index.md
  - Elementos Python: elementosPython.md
  - Ejecución y Depuración: depuracion.md
  - Pruebas: pruebas.md
  - Sandbox: sandbox.md
  - Reflexion: reflexion.md

# -------------------------------------------------------------
# DIRECTORIOS
# -------------------------------------------------------------
doc_dir: docs 
